const termsOfService = {
  INTRODUCTION: [
    "Thank you (\u201cyou\u201d, \u201cyour\u201d, \u201cUser\u201d) for viewing this Terms of Service (\u201cAgreement\u201d). ",
    "Digitote Creative Management Services Inc. (\u201cCompany\u201d, \u201cWe\u201d, \u201cus\u201d, \u201cDigitote\u201d) is a start-up from Calgary, Alberta that provides software, products, and other services in the influencer and creative management sector, including the Website/Platform (as defined below, and together, the \u201cServices\u201d). ",
    "We operate and provide the products, services, information, content, and Intellectual Property (as defined herein) at our website at www.digitote.co and the Digitote mobile and desktop application (together, the \u201cWebsite/Platform\u201d). ",
    "This Terms of Service interacts with, and is subject to, and, where reasonably applicable, User is subject to and bound by, the following documents:",
    "- Our Privacy Policy found at <Privacy Policy URL>.",
    "- Our Agency License agreement found at <Agency License Agreement URL>. ",
  ],
  "ACCEPTANCE OF THE WEBSITE/PLATFORM TERMS AND CONDITIONS OF USE\u00a0": [
    "THROUGH CONTINUED USE OR VIEWERSHIP OF THE WEBSITE/PLATFORM AND THE USE OR CONSUMPTION OF DIGITOTE\u2019S PRODUCTS OR SERVICES, YOU AGREE TO BE BOUND BY THIS TERMS OF SERVICE, AND EACH OF THE DOCUMENTS LISTED ABOVE IN THE INTRODUCTION, AND THE OBLIGATIONS AND REQUIREMENTS SET FORTH THEREIN.",

    "The Agreement constitutes a legal contract entered between Digitote and User. The following terms and conditions, together with any documents and/or additional terms that are expressly incorporated by reference, govern your right to use and access the Website/Platform, use Digitote\u2019s Services, or otherwise interact with our content or Intellectual Property (as defined herein). If the Agreement or any terms of the Agreement are unacceptable to you, you must cease using the Website/Platform immediately.\u00a0",
    "By using this Website/Platform, you represent and warrant that you are the legal age of majority under applicable law to form a binding contract with Digitote and meet all the foregoing eligibility requirements. Anyone under the age of 14 is prohibited from using this Website/Platform and anyone age 14 and over must be accompanied and monitored by an adult who has full responsibility for ensuring compliance with this Agreement. If you do not meet all these requirements, you must not access or use the Website/Platform.",
    "If you are using the Website/Platform on behalf of a company or organization, you represent that you have authority to act on behalf of that entity and provide consent and acceptance for that entity.  ",
  ],
  "MODIFICATIONS TO THE AGREEMENT AND WEBSITE/PLATFORM": [
    "Digitote reserves the right, in our sole discretion, to revise and update this Agreement and any aspect of the Website/Platform from time to time. Any and all such modifications are effective immediately upon posting and apply to all access to and continued use of the Website/Platform. You agree to periodically review the terms of service to be aware of any such modifications and your continued use shall be your acceptance of these.\u00a0",
    "The Website/Platform, assets, copy, information, material, and other Intellectual Property (as defined herein) on the Website/Platform may be changed, withdrawn, or terminated at any time in our sole discretion without notice. We will not be liable if, for any reason, all or any part of the Website/Platform is restricted to Users or unavailable at any time or for any period.",
  ],
  "SAFE USE OF THE WEBSITE/PLATFORM": [
    "The security of your personal information is important to us and we use various measures to secure your personal information from accidental loss and unauthorized use. However, the safety and security of your information also depends on you. Users are responsible for obtaining their own access to the Website/Platform. Users are required to ensure that all persons who access the Website/Platform through a User's internet connection are aware and comply with this Agreement.\u00a0",
    "Unfortunately, the transmission of information via the Internet is not completely secure. Although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to Digitote. Any transmission of personal information is at your own risk. We are not responsible for circumvention of any privacy settings or security measures contained on the Website/Platform.",
    "The Website/Platform may from time to time contain links to third-party websites or resources. We do not endorse and are not responsible or liable for the availability or accuracy of such third-party services, or the content, products, or services available from such third-party services.",
    "Your provision of registration information and any submissions you make to the Website/Platform through any functionality you share information including through a form, drop box, upload field, application, comment, review, chat room, e-mail, message board, forum, registration, profile, or other similar functions (collectively, \u201c<b>Interactive Functions</b>\u201d) constitutes your consent to all actions we take with respect to such information consistent with this Agreement and our Privacy Policy, linked above in the Introduction.",
    "Any username, password, or any other piece of information chosen by you, or provided to you as part of our security procedures, must be treated as confidential, and you must not disclose it to any other person or entity. You must exercise caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information. You understand and agree that should you be provided an account, your account is personal to you, and you agree not to provide any other person with access to the Website/Platform or portions of it using your username, password, or other security information. You agree to notify us immediately of any unauthorized access to or use of your username or password or any other breach of security. You also agree to ensure that you logout from your account at the end of each session. You are responsible for any password misuse or any unauthorized access.\u00a0",
    "You are prohibited from attempting to circumvent and from violating the security of the Website/Platform, including, without limitation: (a) accessing content and data that is not intended for you; (b) attempting to breach or breaching the security and/or authentication measures which are not authorized; (c) restricting, disrupting or disabling service to Users, hosts, servers, or networks; (d) illicitly reproducing TCP/IP packet header; (e) disrupting network services and otherwise disrupting Digitote\u2019s owner's ability to monitor the Website/Platform; (f) using any robot, spider, or other automatic device, process, or means to access the Website/Platform for any purpose, including monitoring or copying any of the material on the Website/Platform; (g) introducing any viruses, trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful; (h) attacking the Website/Platform via a denial-of-service (DOS) attack, distributed denial-of-service (DDOS) attack, flooding, mailbombing, or crashing; (i) attempting to lure other Users off the Website/Platform or using the Website/Platform in connection with the distribution of unsolicited commercial messages; (j) copy, store or otherwise access or use any information, including personally identifiable information about any other user, contained on the Website/Platform in any way that is inconsistent with our Privacy Policy, or other agreement that applies to you linked above in the Introduction, or this Agreement or that otherwise violates the privacy rights of users or third parties, and (k) otherwise attempting to interfere with the proper working of the Website/Platform. ",
    "We reserve the right at any time and from time to time, to disable or terminate your account, any username, password, or other identifier, whether chosen by you or provided by us, in our sole discretion for any or no reason, including any violation of any provision of this Agreement.\u00a0",
  ],
  "INTELLECTUAL PROPERTY RIGHTS AND OWNERSHIP": [
    "You understand and agree that all intellectual property belonging to Digitote, including the Website/Platform and its entire contents, features, and functionality, including, all information, files, content, software, code, metadata, data text, displays, graphics, photographs, images, video, audio, music, broadcast, design, presentation, website or platform layout, selection, and arrangement, or any related derivatives or spinoffs, are the sole property of Digitote, its licensors, or other providers of such material and are protected in all forms by intellectual property laws including without limitation, copyright, trademark, patent, trade secret, and any other proprietary rights.\u00a0",
    "Digitote, and all related names, logos, product and service names, designs, images, and slogans are trademarks of Digitote or its affiliates or licensors. You must not use such marks without the prior written permission of Digitote. Other names, logos, product and service names, designs, images, and slogans mentioned, or which appear on the Website/Platform are the trademarks of their respective owners. Use of any such intellectual property, except as expressly authorized, shall constitute an infringement or violation of the rights of the property owner and may be a violation of federal or other laws and could subject the infringer to legal action.",
    "You may only use the Website/Platform for your personal and non-commercial use unless you have received express consent from Digitote and/or as specified otherwise in a license agreement, client agreement, or other agreement formally in writing with Digitote. You shall not directly or indirectly reproduce, compile for an internal database, distribute, modify, create derivative works of, publicly display, publicly perform, republish, download, store, or transmit any of the material on the Website/Platform, in any form or medium whatsoever; except your computer or browser may temporarily store or cache copies of materials being accessed and viewed and you may make temporary copies of information for your personal use.\u00a0",
    "You have no right, title, or interest in or to the Website/Platform or to any materials or content on the Website/Platform or any Intellectual property, and all rights not expressly granted are reserved by Digitote. Any use of the Website/Platform or Intellectual Property not expressly permitted by this Agreement is a breach of this Agreement and may infringe or violate copyright, trademark, and other intellectual property or other proprietary laws, or the rights of a third party.",
    "You represent and warrant that you have all proper rights, consents, authorizations, and licenses to use all material, files, content, data, works, or other intellectual property posted by you, or made available by you, on the Website/Platform, or otherwise made public in connection with the Website/Platform or Digitote or our Services or Intellectual Property, or as otherwise included in a User Submission (together, \u201cUser Copy\u201d) and you shall at all times make with all User Copy give the proper attributions and credits to the author or creator in a manner reasonably viewable by the audience or consumer of such User Copy. ",
    "Users are not<b> </b>permitted to modify copies of any materials, content, data, or Intellectual Property on the Website/Platform nor delete or alter any copyright, trademark, or other proprietary rights notices, including watermarks and author credits. You must not access or use for any commercial purposes any part of the Website/Platform, Intellectual Property, or materials made available through Digitote.",
    "If you print, copy, download, transmit or distribute any part of our Website/Platform or Digitote\u2019s Intellectual Property or the intellectual property of a third party in breach of this Agreement or a third party agreement, your right to use and access the Website/Platform, Intellectual Property, and Services will cease immediately and you must, at our option, return or destroy any copies of the material, content, data, or intellectual property that you printed, copied, downloaded, transmitted, or distributed. ",
  ],
  "USER CONTENT\u00a0": [
    "As a condition of your access and use of the Website/Platform and Digitote Intellectual Property, you agree that you may use the Website/Platform limited only to lawful purposes and in strict compliance with this Agreement.\u00a0",
    'The following content standards apply to any and all such submissions or other content a User submits, posts, publishes, displays, or transmits (collectively \u201c<b>submit</b>\u201d) to the Website/Platform, to other Users or to other persons (collectively "<b>User Content</b>") and any and all Interactive Functions. ',
    "Any and all User Contents must comply with all applicable federal, provincial, local, and international laws, regulations, and terms of service.\u00a0",
    "If User is registering for the Website/Platform, User must register and operate on the Website/Platform using their legal names and accurate information. By registering for the Website/Platform, you hereby warrant and undertake that the information you provide Digitote during the registration process or update after registration is accurate, complete, and up-to-date. If any User Content becomes inaccurate or incomplete after submission, the User hereby agrees to update the User Content as soon as reasonably practical.\u00a0",
    "Without limiting the foregoing, you represent and warrant and agree that your use of the Website/Platform and Intellectual Property and any User Content shall not involve, provide, or contribute any false, inaccurate, or misleading information. User Content shall not impersonate or attempt to impersonate any other person or entity, nor shall it in any manner violate the terms of use of any third-party website linked to the Website/Platform. User Content shall not include any material that is harmful, abusive, discriminatory, or otherwise objectionable, such determination to be made in Digitote\u2019s sole discretion.\u00a0",
    "You acknowledge that Digitote has no obligation to monitor the access to or use of the Website/Platform by any specific user or to review, disable access to, or edit any User Content, but have the right, option, and discretion to do so to (i) operate, secure and improve the Website/Platform (including without limitation for fraud prevention, risk assessment, investigation and customer support purposes); (ii) ensure your compliance with this Agreement; (iii) comply with applicable law or the order or requirement of a court, law enforcement or other administrative agency or governmental body; (iv) respond to User Content that we determine is harmful or objectionable; or (v) as otherwise set forth in this Agreement.",
    "WE RESERVE THE RIGHT TO UNPUBLISH ANY USER CONTENT AND/OR DEACTIVE OR MAKE PRIVATE USER\u2019S ACCOUNT AT ANY TIME, INCLUDING, BUT NOT LIMITED TO, IF YOU ENGAGE IN ANY CONDUCT THAT WE BELIEVE, IN OUR SOLE DISCRETION, IS ABUSIVE, THREATENING, DISHONEST, VIOLENT, HATEFUL, DISRESPECTFUL, OFFENSIVE, OR OTHERWISE DISRUPTIVE TO OUR COMMUNITY, CLIENTS, USERS, NETWORK, OR THE PUBLIC. ",
  ],
  "USER CONTENT: GRANT OF LICENSE\u00a0": [
    "The Website/Platform may contain Interactive Functions allowing User Content on or through the Website/Platform. None of the User Content you submit to the Website/Platform will be subject to any confidentiality by Digitote. By providing any User Content, you grant us and our affiliates, service providers and our respective licensees, successors, and assigns the right to a commercial, world-wide, royalty free, perpetual, irrevocable, non-exclusive license to use, reproduce, modify, perform, display, distribute, monetize and otherwise disclose to third parties any such material for any purpose and according to your account settings and/or incorporate such material into any form, medium or technology throughout the world without compensation to you. You further waive any moral rights or other rights of authorship as a condition of submitting any User Content.",
    "Without limiting anything in this Agreement, by submitting User Content, you declare and warrant that you either are the sole and exclusive owner of all User Content that you make available on or through the Website/Platform or you have all rights, licenses, consents, and releases that are necessary to grant to us the rights in and to such User Content, as contemplated under this Agreement. ",
  ],
  "PLATFORM IS NOT A PUBLISHER": [
    "You understand and agree that you, not Digitote, nor Digitote\u2019s subsidiaries, affiliates, nor their respective directors, officers, employees, agents, service providers, contractors, licensors, suppliers, or successors, are responsible for any User Content you submit, and you are fully responsible and legally liable, including to any third party, for such content, its accuracy, its truthfulness, and your right to use and make it public. ",
    "Digitote shall in no instance be considered or treated as the author, publisher, or speaker of any User Content or other information provided by or made public by User.  ",
    "Digitote is not responsible or legally liable to any third party for any User Content, or the User Content's accuracy, truthfulness, or a User\u2019s right to use and make such User Content public, submitted by you or any other User of the Website/Platform. ",
    "Digitote shall not be held liable on account of any action voluntarily taken in good faith to restrict access to or availability of material, content, data, or User Content that Digitote considers to be obscene, lewd, lascivious, filthy, excessively violent, harassing, or otherwise objectionable, whether or not such material is constitutionally protected, or take any action to enable, disable, make available, or make private any material, content, data, or User Content.  ",
  ],
  "WEBSITE/PLATFORM MONITORING AND ENFORCEMENT, SUSPENSION, AND TERMINATION": [
    "Without limiting anything in this Agreement, Digitote has the right, without provision of notice to:",
    "- Remove or refuse to post on the Website/Platform any User Content for any or no reason in our sole discretion.",
    "- At all times, take such actions with respect to any User Content deemed necessary or appropriate in our sole discretion.",
    "- Take appropriate legal action, including, without limitation, referral to law enforcement or regulatory authority, or notifying the harmed party of any illegal or unauthorized use of the Website/Platform or Website/Platform. Without limiting the foregoing, we have the right to fully cooperate with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone posting any materials on or through the Website/Platform.\u00a0",
    "- Terminate or suspend your access to all or part of the Website/Platform for any or no reason, including, without limitation, any violation of this Agreement.\u00a0",
    "- Remove, make private, or decrease the visibility of your User Content or profile. ",
    "YOU WAIVE AND HOLD HARMLESS DIGITOTE AND ITS PARENT, SUBSIDIARIES, AFFILIATES, AND THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS, AND SUCCESSORS FROM ANY AND ALL CLAIMS RESULTING FROM ANY ACTION TAKEN BY DIGITOTE AND ANY OF THE FOREGOING PARTIES RELATING TO ANY, INVESTIGATIONS BY EITHER DIGITOTE OR SUCH PARTIES OR BY LAW ENFORCEMENT AUTHORITIES.",
    "We have no obligation, nor any responsibility to any party to monitor the Website/Platform or its use, and do not and cannot undertake to review User Content. We cannot ensure prompt removal of objectionable material after it has been posted and we have no liability for any action or inaction regarding transmissions, communications, or content provided by any user or third party, subject to applicable laws.\u00a0",
  ],
  "NO RELIANCE\u00a0": [
    "The content on the Website/Platform is provided for general information purposes only. It is not intended to amount to professional advice on which you should rely. You must obtain more specific or professional advice before taking, or refraining from, any action or inaction on the basis of the content on the Website/Platform.",
    "Although we make reasonable efforts to update the information on the Website/Platform, we make no representations, warranties, or guarantees, whether express or implied, that the information on the Website/Platform is accurate, complete, or up to date. Your use of the Website/Platform is at your own risk and neither Digitote nor its parent, subsidiaries, affiliates, and their respective directors, officers, employees, agents, service providers, contractors, licensors, licensees, suppliers, or successors have any responsibility or liability whatsoever for your use of the Website/Platform.",
    "The Website/Platform may include content provided by third parties, including from other Users and third-party licensors. All statements and/or opinions expressed in any such third-party content, other than the content provided by Digitote, are solely the opinions and the responsibility of the person or entity providing those materials. Such materials or User Content do not necessarily reflect the opinion of Digitote. Digitote nor its parent, subsidiaries, affiliates, and their respective directors, officers, employees, agents, service providers, contractors, licensors, licensees, suppliers, or successors have any responsibility or liability whatsoever to you, or any third party, for the content or accuracy of any third-party materials, including User Content. ",
  ],
  "PRIVACY\u202f POLICY ACCEPTANCE\u00a0": [
    "Without limiting our Privacy Policy, by using the Website/Platform, you provide Digitote express consent and acceptance to our privacy policies and practices, including our use of cookies, data collection, data retention, data usage, marketing, anti-spam and advertising, and all our policies and practices otherwise listed in our Privacy Policy, listed in the introduction section of this Agreement.\u00a0",
  ],
  "THIRD-PARTY WEBSITES AND LINKS": [
    "For your convenience, Digitote may provide links, connections, or pointers to third-party sites. We make no representations about any other websites that may be accessed from Digitote. If you choose to access any such sites, you do so at your own risk. We have no control over the contents of any such third-party sites and accept no responsibility for such sites or for any loss or damage that may arise from your use of them. You are subject to any terms and conditions of such third-party sites.\u00a0",
  ],
  HYPERLINKS: [
    "Any hyperlink in this Agreement is provided for convenience only and is subject to change from time to time as the server, data, or destination changes, or as posts or pages are taken down or moved, and the parties agree that a wrong or missing hyperlink shall not affect the interpretation or enforcement of this Agreement.",
  ],
  "GEOGRAPHIC RESTRICTIONS": [
    "The owner of the Website/Platform is based in Alberta, Canada. We provide the Website/Platform for use only by persons located in Canada. The Website/Platform is not intended for use in any jurisdiction where its use is not permitted. If you access the Website/Platform from outside Alberta, Canada, you do so at your own risk and you are responsible for compliance with local laws of your jurisdiction.",
  ],
  PRICING: [
    "All prices are in Canadian dollars. All prices, unless otherwise specified, are exclusive of GST or other applicable taxes. Unless otherwise specified, GST, or any other applicable taxes, need not be included in any quote, and shall be added to the bill at the time of executing the transaction. ",
  ],
  "MAILING LIST ACCEPTANCE & CASL COMPLIANCE": [
    "By entering into this Agreement, and/or making any positive action to denote your consent to this Agreement, including by checking any checkbox next to a form or interactive function on this website, or entering, submitting, or executing any form or interactive function on this website, you acknowledge and agree that you provide us express consent to send you any Commercial Electronic Message (CEM) or other communication, for commercial and other promotional purposes; and you agree to be added to our mail list until and when you provide us written notice that you wish to unsubscribe; and you agree that you otherwise provide us implied consent by virtue of the relationship between you and us and/or your posting or making available your information online unaccompanied by a statement that you do not wish to receive CEMs.    ",
  ],
  "DISCLAIMER OF WARRANTIES": [
    ,
    "YOU UNDERSTAND AND AGREE THAT YOUR USE OF THE WEBSITE/PLATFORM, ITS CONTENT, AND ANY SERVICES OR ITEMS FOUND OR ATTAINED THROUGH THE WEBSITE/PLATFORM IS AT YOUR OWN RISK. THE WEBSITE/PLATFORM, ITS CONTENT, AND ANY SERVICES OR ITEMS FOUND OR ATTAINED THROUGH THE WEBSITE/PLATFORM OR SERVICE ARE PROVIDED ON AN \u2018AS IS\u2019 AND \u2018AS AVAILABLE\u2019 BASIS, WITHOUT ANY WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.",
    "NEITHER DIGITOTE NOR ITS PARENT, SUBSIDIARIES, AFFILIATES, OR THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS, OR SUCCESSORS MAKE ANY WARRANTY, REPRESENTATION, OR ENDORSEMENT WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, SUITABILITY, ACCURACY, CURRENCY, OR AVAILABILITY OF THE WEBSITE/PLATFORM OR ITS CONTENTS. WITHOUT LIMITING THE FOREGOING, NEITHER DIGITOTE NOR ITS PARENT, SUBSIDIARIES, AFFILIATES OR THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS, OR SUCCESSORS REPRESENT OR WARRANT THAT THE WEBSITE/PLATFORM, ITS CONTENT, OR ANY SERVICES OR ITEMS FOUND OR ATTAINED THROUGH THE WEBSITE/PLATFORM WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT OUR WEBSITE/PLATFORM OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.",
    "WE CANNOT AND DO NOT GUARANTEE OR WARRANT THAT FILES OR DATA AVAILABLE FOR DOWNLOADING FROM THE INTERNET OR THE WEBSITE/PLATFORM WILL BE FREE OF VIRUSES OR OTHER DESTRUCTIVE CODE. YOU ARE SOLELY AND ENTIRELY RESPONSIBLE FOR YOUR USE OF THE WEBSITE/PLATFORM AND YOUR COMPUTER, INTERNET, AND DATA SECURITY. TO THE FULLEST EXTENT PROVIDED BY LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY DENIAL-OF-SERVICE ATTACK, DISTRIBUTED DENIAL-OF-SERVICE ATTACK, OVERLOADING, FLOODING, MAILBOMBING, OR CRASHING, VIRUSES, TROJAN HORSES, WORMS, LOGIC BOMBS, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE WEBSITE/PLATFORM OR ANY SERVICES OR ITEMS FOUND OR ATTAINED THROUGH THE WEBSITE/PLATFORM OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED ON IT, OR ON ANY WEBSITE LINKED TO IT.",
  ],
  "LIMITATION ON LIABILITY": [
    "EXCEPT WHERE SUCH EXCLUSIONS ARE PROHIBITED BY LAW, UNDER NO CIRCUMSTANCE WILL DIGITOTE NOR ITS PARENT, SUBSIDIARIES, AFFILIATES OR THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SERVICE PROVIDERS, CONTRACTORS, LICENSORS, LICENSEES, SUPPLIERS, OR SUCCESSORS BE LIABLE FOR NEGLIGENCE, GROSS NEGLIGENCE, NEGLIGENT MISREPRESENTATION, FUNDAMENTAL BREACH, DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING, BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, BREACH OF PRIVACY, OR OTHERWISE, EVEN IF THE PARTY WAS ALLEGEDLY ADVISED OR HAD REASON TO KNOW, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, OR RELIANCE ON, THE WEBSITE/PLATFORM, ANY LINKED WEBSITES OR SUCH OTHER THIRD-PARTY WEBSITES, NOR ANY WEBSITE CONTENT, MATERIALS, POSTING, OR INFORMATION THEREON EVEN IF THE PARTY WAS ALLEGEDLY ADVISED OR HAD REASON TO KNOW.",
  ],
  INDEMNIFICATION: [
    "To the maximum extent permitted by applicable law, you agree to defend, indemnify, and hold harmless Digitote, its parent, subsidiaries, affiliates, and their respective directors, officers, employees, agents, service providers, contractors, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your breach of this Agreement and/or your use, access to, or consumption of the Website/Platform or Intellectual property, including, but not limited to, User Content, User Copy, third-party sites, your unauthorized use, download, sale, or transmission of a third party\u2019s property, or your infringement or breach of a third party\u2019s rights or a third party agreement.",
  ],
  "GOVERNING LAW AND CHOICE OF FORUM": [
    "The Website/Platform and this Agreement will be governed by and construed in accordance with the laws of Alberta and the federal laws of Canada applicable therein, without giving effect to any choice or conflict of law provision, principle, or rule. Any action or proceeding arising out of or relating to the Website/Platform and under this Agreement will be instituted in the courts of Alberta and/or the Federal Court of Canada, and each party irrevocably submits to the exclusive jurisdiction of such courts in any such action or proceeding. You waive any and all objections to the exercise of jurisdiction over you by such courts and to the venue of such courts.",
  ],
  "WAIVER\u00a0": [
    "Except as otherwise set forth in this Agreement, no failure to exercise, or delay in exercising, any right, remedy, power, or privilege arising from this Agreement operates, or may be construed, as a waiver thereof; and no single or partial exercise of any right, remedy, power, or privilege hereunder precludes any other or further exercise thereof or the exercise of any other right, remedy, power, or privilege.",
  ],
  SEVERABILITY: [
    "If any term or provision of this Agreement is invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability shall not affect any other term or provision of this Agreement or invalidate or render unenforceable such term or provision in any other jurisdiction.",
  ],
  "ENTIRE AGREEMENT": [
    "This Agreement, and any documents listed above in the introduction, including our Privacy Policy and Agency License Agreement, constitute the sole and entire Agreement between you and Digitote regarding the use and access of the Website/Platform and supersedes all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, regarding such subject matter.\u00a0",
  ],
  "CONTACT & NOTICES": [
    "Digitote Creative Management Services Inc. is a corporation duly incorporated in Alberta, Canada with a business address of 409B 13 Street NW Calgary, Alberta T2N 1Z3, Canada. ",
    "All notices and communications to Digitote shall be delivered in writing via email to legal@digitote.co, Attention: Privacy Officer.  ",
    "All notices and communications to User shall be delivered to User in writing via email to the email address they used to contact Digitote and/or the email address we have on file for User.  ",
    "If submitting a notice, complaint or request to withdraw consent or remove your account, content, data, or information from the Website/Platform, please particularize and substantiate all information and evidence Digitote needs to comply with such notice, complaint or request, including to comply with all relevant rules, regulations, and our Privacy Policy, within TEN (10) days of the circumstances of such notice, complaint, or request being made known to User.  ",
    "If you believe that someone is, through the use of our Website/Platform, unlawfully infringing the copyright(s) in a work belonging to you or someone else, and you wish to have the allegedly infringing material removed, send the following information to us at the email below: ",
    "- Identification of the copyrighted work(s) that you claim to have been infringed, including hyperlinks and screenshots.",
    "- Identification of the material on our services that you claim is infringing and that you request us to remove, including hyperlinks and screenshots. ",
    "- Sufficient information to permit us to locate such material.",
    "- A statement that you have a good faith belief that use of the objectionable material is not authorized by the copyright owner, its agent, or under the law. ",
    "- A statement that the information in the notification is accurate, and under penalty of perjury, that you are either the owner of the copyright that has allegedly been infringed or that you are authorized to act on behalf of the copyright owner",
    "- Your address, telephone number, and e-mail address. ",
    "- Your physical or electronic signature.",
  ],
};

export default termsOfService;
